from sqlalchemy.orm import relationship
from sqlalchemy.sql.schema import ForeignKey, MetaData
from db.database import Base
from sqlalchemy import Column
from sqlalchemy.sql.sqltypes import Integer, String, DateTime, Float, Date


class DbOrderData(Base):
    __tablename__ = "order_data"
    id = Column(Integer, primary_key=True, index=True)
    sku = Column(String(100))
    account = Column(String(10))
    market_order_id = Column(String(100))
    order_number = Column(String(100))
    order_count = Column(Integer)
    store = Column(String(20))
    product_name = Column(String(500))
    fst_link = Column(String(1000))
    snd_link = Column(String(1000))
    order_qty = Column(Integer)
    unit_price = Column(Float)
    local_trans_fee = Column(Float)
    sell_price = Column(Float)
    package = Column(Integer)
    product_weight = Column(Float)
    volume_weight = Column(Float)
    hs_code = Column(Integer)
    bdj_code = Column(Integer)
    asin = Column(String(100))
    margin = Column(Float)
    market_prod_number = Column(String(100))
    sell_link = Column(String(1000))
    bdj_fee = Column(Float)
    tax = Column(Float)
    sold_qty = Column(Integer)
    big_ctg = Column(Integer)
    tax_ctg = Column(String(50))
    image_link = Column(String(1000))
    brand = Column(String(300))
    eng_prd_name = Column(String(500))
    competition_link = Column(String(1000))
    selling_time = Column(DateTime)
    memo = Column(String(1000))


class DbProductDb(Base):
    __tablename__ = "product_db"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(2))
    cp_prd_no = Column(String(12))
    ss_prd_no = Column(String(12))
    st_prd_no = Column(String(12))
    gm_prd_no = Column(String(12))
    au_prd_no = Column(String(12))
    lo_prd_no = Column(String(12))
    ip_prd_no = Column(String(12))
    r1 = Column(String(100))
    r2 = Column(String(100))
    r3 = Column(String(12))
    r4 = Column(String(12))
    r5 = Column(String(12))
    r6 = Column(String(12))
    s1 = Column(String(50))
    s2 = Column(String(50))
    s3 = Column(String(50))
    s4 = Column(String(50))
    s5 = Column(String(50))
    s6 = Column(String(50))
    sold_qty = Column(Integer)
    big_ctg = Column(Integer)
    tax_ctg = Column(String(6))
    img_no = Column(Integer)
    product_weight = Column(Float)
    volume_weight = Column(Float)
    asin = Column(String(12))
    product_name = Column(String(100))
    keyword = Column(String(20))
    search_tag = Column(String(100))
    rr1 = Column(String(100))
    option_tag = Column(Integer)
    fst_link = Column(String(100))
    snd_link = Column(String(100))
    eng_prd_name = Column(String(220))
    image_link = Column(String(50))
    country_code = Column(String(5))
    country_name = Column(String(8))
    brand = Column(String(50))
    hs_code = Column(Integer)
    bdj_code = Column(Integer)
    option = Column(String(20))
    package = Column(Integer)
    local_trans_fee = Column(Float)
    tax = Column(Integer)
    order_qty = Column(Integer)
    unit_price = Column(Float)
    sourcing_price = Column(Float)
    bdj_fee = Column(Integer)
    competition_link = Column(String(50))
    competition_price = Column(Integer)
    competition_trans_fee = Column(Integer)
    cp_sell_link = Column(String(50))
    cp_sell_price = Column(Integer)
    cp_sell_trans_fee = Column(Integer)
    cp_commission = Column(Integer)
    cp_margin = Column(Integer)
    ss_sell_link = Column(String(50))
    ss_sell_price = Column(Integer)
    ss_sell_trans_fee = Column(Integer)
    ss_commission = Column(Integer)
    ss_margin = Column(Integer)
    st_sell_link = Column(String(50))
    st_sell_price = Column(Integer)
    st_sell_trans_fee = Column(Integer)
    st_commission = Column(Integer)
    st_margin = Column(Integer)
    gm_sell_link = Column(String(50))
    gm_sell_price = Column(Integer)
    gm_sell_trans_fee = Column(Integer)
    gm_commission = Column(Integer)
    gm_margin = Column(Integer)
    au_sell_link = Column(String(50))
    au_sell_price = Column(Integer)
    au_sell_trans_fee = Column(Integer)
    au_commission = Column(Integer)
    au_margin = Column(Integer)
    lo_sell_link = Column(String(50))
    lo_sell_price = Column(Integer)
    lo_sell_trans_fee = Column(Integer)
    lo_commission = Column(Integer)
    lo_margin = Column(Integer)
    ip_sell_link = Column(String(50))
    ip_sell_price = Column(Integer)
    ip_sell_trans_fee = Column(Integer)
    ip_commission = Column(Integer)
    ip_margin = Column(Integer)


class CandidateDB(Base):
    __tablename__ = "candidate"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(2))
    cp_prd_no = Column(String(12))
    ss_prd_no = Column(String(12))
    st_prd_no = Column(String(12))
    gm_prd_no = Column(String(12))
    au_prd_no = Column(String(12))
    lo_prd_no = Column(String(12))
    ip_prd_no = Column(String(12))
    r1 = Column(String(12))
    r2 = Column(String(12))
    r3 = Column(String(12))
    r4 = Column(String(12))
    r5 = Column(String(12))
    r6 = Column(String(12))
    s1 = Column(String(50))
    s2 = Column(String(50))
    s3 = Column(String(50))
    s4 = Column(String(50))
    s5 = Column(String(50))
    s6 = Column(String(50))
    sold_qty = Column(Integer)
    big_ctg = Column(Integer)
    tax_ctg = Column(String(6))
    img_no = Column(Integer)
    product_weight = Column(Float)
    volume_weight = Column(Float)
    asin = Column(String(12))
    product_name = Column(String(200))
    keyword = Column(String(20))
    search_tag = Column(String(100))
    rr1 = Column(String(100))
    option_tag = Column(Integer)
    fst_link = Column(String(100))
    snd_link = Column(String(100))
    eng_prd_name = Column(String(220))
    image_link = Column(String(50))
    country_code = Column(String(5))
    country_name = Column(String(8))
    brand = Column(String(50))
    hs_code = Column(Integer)
    bdj_code = Column(Integer)
    option = Column(String(20))
    package = Column(Integer)
    local_trans_fee = Column(Float)
    tax = Column(Integer)
    order_qty = Column(Integer)
    unit_price = Column(Float)
    sourcing_price = Column(Float)
    bdj_fee = Column(Integer)
    competition_link = Column(String(50))
    competition_price = Column(Integer)
    competition_trans_fee = Column(Integer)
    cp_sell_link = Column(String(50))
    cp_sell_price = Column(Integer)
    cp_sell_trans_fee = Column(Integer)
    cp_commission = Column(Integer)
    cp_margin = Column(Integer)
    ss_sell_link = Column(String(50))
    ss_sell_price = Column(Integer)
    ss_sell_trans_fee = Column(Integer)
    ss_commission = Column(Integer)
    ss_margin = Column(Integer)
    st_sell_link = Column(String(50))
    st_sell_price = Column(Integer)
    st_sell_trans_fee = Column(Integer)
    st_commission = Column(Integer)
    st_margin = Column(Integer)
    gm_sell_link = Column(String(50))
    gm_sell_price = Column(Integer)
    gm_sell_trans_fee = Column(Integer)
    gm_commission = Column(Integer)
    gm_margin = Column(Integer)
    au_sell_link = Column(String(50))
    au_sell_price = Column(Integer)
    au_sell_trans_fee = Column(Integer)
    au_commission = Column(Integer)
    au_margin = Column(Integer)
    lo_sell_link = Column(String(50))
    lo_sell_price = Column(Integer)
    lo_sell_trans_fee = Column(Integer)
    lo_commission = Column(Integer)
    lo_margin = Column(Integer)
    ip_sell_link = Column(String(50))
    ip_sell_price = Column(Integer)
    ip_sell_trans_fee = Column(Integer)
    ip_commission = Column(Integer)
    ip_margin = Column(Integer)


class DbExchangeRate(Base):
    __tablename__ = "exchange_rate"
    date = Column(Date, primary_key=True, index=True)
    USD = Column(Float)
    JPY = Column(Float)
    EUR = Column(Float)
    GBP = Column(Float)
    CAD = Column(Float)
    AUD = Column(Float)
    NZD = Column(Float)
    CNH = Column(Float)
    HKD = Column(Float)


class KgTariff(Base):
    __tablename__ = "kg_tariff"
    kg_idx = Column(Float, primary_key=True, index=True)
    de = Column(Integer)
    uk = Column(Integer)
    es = Column(Integer)
    jp_air = Column(Integer)
    jp_ves = Column(Integer)
    jp_ems = Column(Integer)
    cn_sh_air = Column(Integer)
    cn_sh_ves = Column(Integer)
    cn_qd_air = Column(Integer)
    cn_qd_ves = Column(Integer)


class LbsTariff(Base):
    __tablename__ = "lbs_tariff"
    lbs = Column(Integer, primary_key=True, index=True)
    us_or = Column(Integer)
    us_nj = Column(Integer)
    us_ca = Column(Integer)


class HsCode(Base):
    __tablename__ = "hs_code"
    big_cat = Column(Integer)
    big_cat_name = Column(String(20))
    hs_code = Column(Integer)
    code_name = Column(String(30))
    tax_cat = Column(String(20))
    cat_code = Column(Integer, primary_key=True, nullable=True)
    cat_name = Column(String(50))
    ew_big_cat = Column(String(10))
    ew_cat_no = Column(String(30))
    ew_cat_name = Column(String(300))
    cp_cat_ref = Column(String(300))


class ConsolidationDB(Base):
    __tablename__ = "consolidation_db"
    order_no = Column(String(100))
    market = Column(String(20))
    store_order_id = Column(String(100), primary_key=True)
    order_date = Column(String(100))
    product_name = Column(String(200))
    sku = Column(String(100))
    total_price = Column(Integer)
    pur_cnt = Column(Integer)
    pack_cnt = Column(Integer)
    orderer = Column(String(100))
    receiver = Column(String(100))
    receiver_phone = Column(String(100))
    post_code = Column(String(100))
    address = Column(String(100))
    message = Column(String(100))
    pccc = Column(String(100))
    r_s_date = Column(String(100))
    account = Column(String(100))
    note1 = Column(String(100))
    note2 = Column(String(100))


class IPOrderIdHistoryDB(Base):
    __tablename__ = "ip_order_id_history_db"
    ip_order_id = Column(String(100), primary_key=True, index=True)
    upload_time = Column(DateTime)


class PrdNumAndPriceDB(Base):
    __tablename__ = "prd_num_and_price"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(20))
    cp_prd_no = Column(String(50))
    ss_prd_no = Column(String(50))
    st_prd_no = Column(String(50))
    gm_prd_no = Column(String(50))
    au_prd_no = Column(String(50))
    lo_prd_no = Column(String(50))
    ip_prd_no = Column(String(50))
    BLOCK = Column(String(50))
    cp_sell_price = Column(Integer)
    ss_sell_price = Column(Integer)
    st_sell_price = Column(Integer)
    gm_sell_price = Column(Integer)
    au_sell_price = Column(Integer)
    lo_sell_price = Column(Integer)
    ip_sell_price = Column(Integer)


# =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=*


class CPPrdInfo(Base):
    __tablename__ = "CP_prd_info"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(3))
    prd_no = Column(String(50))
    prd_name = Column(String(200))
    stock_qty = Column(Integer)
    selling_price = Column(Integer)


class SSPrdInfo(Base):
    __tablename__ = "SS_prd_info"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(3))
    prd_no = Column(String(50))
    prd_name = Column(String(200))
    stock_qty = Column(Integer)
    selling_price = Column(Integer)


class STPrdInfo(Base):
    __tablename__ = "ST_prd_info"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(3))
    prd_no = Column(String(50))
    prd_name = Column(String(200))
    stock_qty = Column(Integer)
    selling_price = Column(Integer)


class IPPrdInfo(Base):
    __tablename__ = "IP_prd_info"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(3))
    prd_no = Column(String(50))
    prd_name = Column(String(200))
    stock_qty = Column(Integer)
    selling_price = Column(Integer)


class AUPrdInfo(Base):
    __tablename__ = "AU_prd_info"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(3))
    prd_no = Column(String(50))
    prd_name = Column(String(200))
    stock_qty = Column(Integer)
    selling_price = Column(Integer)


class GMPrdInfo(Base):
    __tablename__ = "GM_prd_info"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(3))
    prd_no = Column(String(50))
    prd_name = Column(String(200))
    stock_qty = Column(Integer)
    selling_price = Column(Integer)


class LOPrdInfo(Base):
    __tablename__ = "LO_prd_info"
    sku = Column(String(12), primary_key=True, index=True)
    account = Column(String(3))
    prd_no = Column(String(50))
    prd_name = Column(String(200))
    stock_qty = Column(Integer)
    selling_price = Column(Integer)


# =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=* =*=*=*=*
